import { expect, test } from "bun:test"
import { ResponseRepetition } from "../src/response-repetition"

test("removes repeated prose generated by a local model loop", () => {
  const first =
    "Ви запитали, як вас звати. Я не знаю вашого імені, тому що ви його ще не повідомляли. Скажіть своє ім’я, і я зможу звертатися до вас правильно."
  const repeated =
    "Я не знаю вашого імені, тому що ви його ще не повідомляли. Ви можете сказати своє ім’я, і тоді я зможу звертатися до вас правильно."
  const result = ResponseRepetition.normalize(`${first}\n\n${repeated}\n\nЧим ще допомогти?`)

  expect(result).toBe(`${first}\n\nЧим ще допомогти?`)
})

test("preserves structured lists and code even when vocabulary overlaps", () => {
  const input = `Перевірено такі файли та їхню поведінку в поточній реалізації системи:\n\n- src/one.ts: перший обробник\n- src/two.ts: другий обробник\n\n\`\`\`ts\nconst first = true\n\nconst second = true\n\`\`\``

  expect(ResponseRepetition.normalize(input)).toBe(input)
})

test("leaves short direct answers unchanged", () => {
  expect(ResponseRepetition.normalize("Я ще не знаю вашого імені.")).toBe("Я ще не знаю вашого імені.")
})

test("detects the same tool call across separate provider turns", () => {
  const history = [
    { tool: "grep", input: { include: "*.php", pattern: "journal" } },
    { tool: "grep", input: { pattern: "journal", include: "*.php" } },
  ]

  expect(
    ResponseRepetition.repeatedToolCall(history, {
      tool: "grep",
      input: { include: "*.php", pattern: "journal" },
    }),
  ).toBe(true)
  expect(ResponseRepetition.repeatedToolCall(history, { tool: "grep", input: { pattern: "offender" } })).toBe(false)
})

test("groups repaired invalid calls by the intended tool instead of changing error text", () => {
  const history = [
    { tool: "invalid", input: { tool: "grep", error: "missing pattern" } },
    { tool: "invalid", input: { tool: "grep", error: "invalid input at path query" } },
  ]

  expect(
    ResponseRepetition.repeatedToolCall(history, {
      tool: "invalid",
      input: { tool: "grep", error: "schema mismatch" },
    }),
  ).toBe(true)
})

test("stops a second malformed call for the same intended tool even after other tool activity", () => {
  const history = [
    { tool: "invalid", input: { tool: "grep", error: "unterminated JSON" } },
    { tool: "read", input: { filePath: "/tmp/example" } },
  ]
  expect(
    ResponseRepetition.repeatedInvalidToolCall(history, {
      tool: "invalid",
      input: { tool: "grep", error: "different malformed JSON" },
    }),
  ).toBe(true)
  expect(
    ResponseRepetition.repeatedInvalidToolCall(history, {
      tool: "invalid",
      input: { tool: "read", error: "unterminated JSON" },
    }),
  ).toBe(false)
})
