export const instructorConsole = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Embodied Agent · Instructor</title><style>
:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif;background:#111019;color:#f4f1ff}*{box-sizing:border-box}body{margin:0;padding:28px}.shell{max-width:1200px;margin:auto}.top{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:24px}.muted{color:#aaa3c8}.status{padding:5px 10px;border-radius:999px;background:#2b2738}.ok{color:#66e2b8}.bad{color:#ff929f}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:18px}.card{background:#1b1826;border:1px solid #39334b;border-radius:14px;padding:18px;margin-bottom:18px}h1,h2{margin:0 0 10px}h1{font-size:25px}h2{font-size:18px}.actions{display:flex;flex-wrap:wrap;gap:8px}button,.button,input,textarea{font:inherit;color:inherit;border:1px solid #514963;background:#282337;border-radius:8px;padding:10px 12px}button,.button{cursor:pointer;text-decoration:none}button:hover{background:#373047}button:disabled{opacity:.45;cursor:not-allowed}input,textarea{width:100%;margin-top:6px}textarea{min-height:76px;resize:vertical}.row{padding:10px 0;border-top:1px solid #332e42}.row:first-child{border-top:0}.evidence{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.timeline{max-height:360px;overflow:auto;font-family:ui-monospace,monospace;font-size:12px}.error{color:#ff929f;min-height:20px}.hint{color:#56d9e0}.conflict{border-color:#a04f59}@media(max-width:800px){body{padding:16px}.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}
</style></head><body><main class="shell">
<div class="top"><div><h1>Live Instructor Console</h1><div class="muted">Supervised local Unity Desktop / Quest session</div></div><div><a class="button" href="/">Runtime Control Center</a> <span id="connection" class="status">Connecting…</span></div></div>
<div id="conflict" class="card conflict" hidden><h2>Unsupported session conflict</h2><p>Beta supports one active trainee. Stop the additional scenario before issuing instructor commands.</p></div>
<div class="grid"><section>
<div class="card"><h2>Active training</h2><div id="scenario" class="muted">No active scenario</div><div class="actions" style="margin-top:16px"><button data-command="pause">Pause</button><button data-command="resume">Resume</button><button data-command="retry_current_step">Retry current step</button><button data-command="terminate">Terminate safely</button></div><div id="controlError" class="error"></div></div>
<div class="card"><h2>Text hint</h2><textarea id="hint" maxlength="500" placeholder="A short instruction shown in the trainee HUD"></textarea><div class="actions"><button id="sendHint">Send hint</button><span id="hintCount" class="muted">0 / 500</span></div><div id="hintError" class="error"></div></div>
<div class="card"><h2>Instructor evidence</h2><p class="muted">Only evidence rules explicitly owned by the instructor can be confirmed.</p><div id="evidence">No instructor-owned evidence on the current step.</div><div id="evidenceError" class="error"></div></div>
</section><aside>
<div class="card"><h2>Pending approvals</h2><div id="approvals" class="muted">No pending approvals</div></div>
<div class="card"><h2>Runtime</h2><div id="runtime" class="muted">Loading…</div></div>
<div class="card"><h2>Audit timeline</h2><div id="timeline" class="timeline"></div></div>
</aside></div></main><script>
const state={snapshot:null,busy:false};const esc=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const post=async(path,body)=>{const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.message||value.error||'Request failed');return value};
const active=()=>state.snapshot?.active;const commandBody=(command)=>({requestID:crypto.randomUUID(),command,runID:active().runID,scenarioRevision:active().scenarioRevision,expectedStepID:active().currentStepID,instructorID:active().instructorID});
function render(value){state.snapshot=value;const session=value.active;const canControl=!!session?.instructorID;document.querySelector('#connection').textContent=value.status;document.querySelector('#connection').className='status '+(value.status==='active'?'ok':value.status==='conflict'?'bad':'');document.querySelector('#conflict').hidden=value.status!=='conflict';document.querySelector('#scenario').innerHTML=session?'<strong>'+esc(session.scenarioID)+'</strong> · revision '+esc(session.scenarioRevision)+'<br>Trainee: '+esc(session.traineeID||'unassigned')+' · Instructor: '+esc(session.instructorID||'identity required')+' · '+esc(session.status)+'<br>Step: '+esc(session.currentStepID||'—')+' · attempt '+esc(session.attempt)+' · '+esc(Math.ceil(session.timeoutRemainingMs/1000))+' s remaining':'No active scenario';document.querySelectorAll('[data-command]').forEach((button)=>{const command=button.dataset.command;button.disabled=!canControl||state.busy||(command==='pause'&&session.status!=='running')||((command==='resume'||command==='retry_current_step')&&session.status!=='paused')});document.querySelector('#sendHint').disabled=!canControl||state.busy;
const approvals=value.pendingApprovals||[];document.querySelector('#approvals').innerHTML=approvals.length?approvals.map((item)=>{const expired=!item.expiresAt||item.expiresAt<=Date.now();const disabled=state.busy||expired||!canControl?' disabled':'';return '<div class="row"><strong>'+esc(item.title)+'</strong><br><span class="muted">'+esc(item.risk)+' · '+esc(item.actionID)+' · '+(expired?'expired':'expires '+new Date(item.expiresAt).toLocaleTimeString())+'</span><pre>'+esc(JSON.stringify(item.args,null,2))+'</pre><div class="actions"><button data-approval="'+esc(item.id)+'" data-approved="true"'+disabled+'>Allow once</button><button data-approval="'+esc(item.id)+'" data-approved="false"'+disabled+'>Deny</button></div></div>'}).join(''):'<span class="muted">No pending approvals</span>';
const ids=session?.instructorEvidenceIDs||[];document.querySelector('#evidence').innerHTML=ids.length?ids.map((id)=>'<div class="row"><strong>'+esc(id)+'</strong><label>Value<input data-evidence-value="'+esc(id)+'" value="verified"></label><label>Reason<input data-evidence-reason="'+esc(id)+'" maxlength="500" placeholder="Why the instructor accepts this evidence"></label><button data-evidence="'+esc(id)+'"'+(state.busy||!canControl?' disabled':'')+'>Confirm evidence</button></div>').join(''):'<span class="muted">No instructor-owned evidence on the current step.</span>';
document.querySelector('#runtime').innerHTML='Model: '+esc(value.modelRuntime?.selectedModel?.modelID||'unconfigured')+'<br>STT: '+esc(value.voice?.transcription)+' · TTS: '+esc(value.voice?.synthesis);document.querySelector('#timeline').innerHTML=(value.timeline||[]).slice().reverse().map((item)=>'<div class="row"><span class="muted">#'+esc(item.sequence)+'</span> '+esc(item.event.type)+'<br>'+esc(JSON.stringify(item.event))+'</div>').join('');bindDynamic()}
async function act(path,body,errorID){state.busy=true;render(state.snapshot);document.querySelector(errorID).textContent='';try{await post(path,body)}catch(error){document.querySelector(errorID).textContent=error.message}finally{state.busy=false;if(state.snapshot)render(state.snapshot)}}
document.querySelectorAll('[data-command]').forEach((button)=>button.onclick=()=>act('/v1/instructor/control',commandBody(button.dataset.command),'#controlError'));document.querySelector('#hint').oninput=(event)=>document.querySelector('#hintCount').textContent=event.target.value.length+' / 500';document.querySelector('#sendHint').onclick=()=>act('/v1/instructor/hint',{...commandBody('hint'),text:document.querySelector('#hint').value},'#hintError');
function bindDynamic(){document.querySelectorAll('[data-approval]').forEach((button)=>button.onclick=()=>act('/v1/instructor/approvals/'+encodeURIComponent(button.dataset.approval),{approved:button.dataset.approved==='true',instructorID:active()?.instructorID},'#controlError'));document.querySelectorAll('[data-evidence]').forEach((button)=>button.onclick=()=>{const id=button.dataset.evidence;act('/v1/instructor/evidence',{...commandBody('evidence'),evidenceID:id,value:document.querySelector('[data-evidence-value="'+CSS.escape(id)+'"]').value,reason:document.querySelector('[data-evidence-reason="'+CSS.escape(id)+'"]').value},'#evidenceError')})}
const events=new EventSource('/v1/instructor/events');events.addEventListener('snapshot',(event)=>render(JSON.parse(event.data)));events.addEventListener('instructor',()=>fetch('/v1/instructor/session').then((response)=>response.json()).then(render));events.onerror=()=>{document.querySelector('#connection').textContent='reconnecting'};fetch('/v1/instructor/session').then((response)=>response.json()).then(render);
</script></body></html>`
