// Generated by @opencode-ai/httpapi-codegen. Do not edit.
import { Effect, Stream, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { ClientApi } from "../contract"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>

const mapClientError = <E>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

const Endpoint0_0 = (raw: RawClient["server.health"]) => () =>
  raw["health.get"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup0 = (raw: RawClient["server.health"]) => ({ get: Endpoint0_0(raw) })

type Endpoint1_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
type Endpoint1_0Input = { readonly location?: Endpoint1_0Request["query"]["location"] }
const Endpoint1_0 = (raw: RawClient["server.location"]) => (input?: Endpoint1_0Input) =>
  raw["location.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup1 = (raw: RawClient["server.location"]) => ({ get: Endpoint1_0(raw) })

type Endpoint2_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
type Endpoint2_0Input = { readonly location?: Endpoint2_0Request["query"]["location"] }
const Endpoint2_0 = (raw: RawClient["server.agent"]) => (input?: Endpoint2_0Input) =>
  raw["agent.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup2 = (raw: RawClient["server.agent"]) => ({ list: Endpoint2_0(raw) })

type Endpoint3_0Request = Parameters<RawClient["server.session"]["session.list"]>[0]
type Endpoint3_0Input = {
  readonly workspace?: Endpoint3_0Request["query"]["workspace"]
  readonly limit?: Endpoint3_0Request["query"]["limit"]
  readonly order?: Endpoint3_0Request["query"]["order"]
  readonly search?: Endpoint3_0Request["query"]["search"]
  readonly directory?: Endpoint3_0Request["query"]["directory"]
  readonly project?: Endpoint3_0Request["query"]["project"]
  readonly subpath?: Endpoint3_0Request["query"]["subpath"]
  readonly cursor?: Endpoint3_0Request["query"]["cursor"]
}
const Endpoint3_0 = (raw: RawClient["server.session"]) => (input?: Endpoint3_0Input) =>
  raw["session.list"]({
    query: {
      workspace: input?.["workspace"],
      limit: input?.["limit"],
      order: input?.["order"],
      search: input?.["search"],
      directory: input?.["directory"],
      project: input?.["project"],
      subpath: input?.["subpath"],
      cursor: input?.["cursor"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_1Request = Parameters<RawClient["server.session"]["session.create"]>[0]
type Endpoint3_1Input = {
  readonly id?: Endpoint3_1Request["payload"]["id"]
  readonly agent?: Endpoint3_1Request["payload"]["agent"]
  readonly model?: Endpoint3_1Request["payload"]["model"]
  readonly location?: Endpoint3_1Request["payload"]["location"]
  readonly mode?: Endpoint3_1Request["payload"]["mode"]
  readonly jarvis?: Endpoint3_1Request["payload"]["jarvis"]
}
const Endpoint3_1 = (raw: RawClient["server.session"]) => (input?: Endpoint3_1Input) =>
  raw["session.create"]({
    payload: {
      id: input?.["id"],
      agent: input?.["agent"],
      model: input?.["model"],
      location: input?.["location"],
      mode: input?.["mode"],
      jarvis: input?.["jarvis"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const Endpoint3_2 = (raw: RawClient["server.session"]) => () =>
  raw["session.active"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_3Request = Parameters<RawClient["server.session"]["session.get"]>[0]
type Endpoint3_3Input = { readonly sessionID: Endpoint3_3Request["params"]["sessionID"] }
const Endpoint3_3 = (raw: RawClient["server.session"]) => (input: Endpoint3_3Input) =>
  raw["session.get"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_4Request = Parameters<RawClient["server.session"]["session.updateJarvis"]>[0]
type Endpoint3_4Input = {
  readonly sessionID: Endpoint3_4Request["params"]["sessionID"]
  readonly profileID?: Endpoint3_4Request["payload"]["profileID"]
  readonly profileRevision?: Endpoint3_4Request["payload"]["profileRevision"]
  readonly mode?: Endpoint3_4Request["payload"]["mode"]
  readonly inbox?: Endpoint3_4Request["payload"]["inbox"]
}
const Endpoint3_4 = (raw: RawClient["server.session"]) => (input: Endpoint3_4Input) =>
  raw["session.updateJarvis"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      profileID: input["profileID"],
      profileRevision: input["profileRevision"],
      mode: input["mode"],
      inbox: input["inbox"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_5Request = Parameters<RawClient["server.session"]["session.remove"]>[0]
type Endpoint3_5Input = { readonly sessionID: Endpoint3_5Request["params"]["sessionID"] }
const Endpoint3_5 = (raw: RawClient["server.session"]) => (input: Endpoint3_5Input) =>
  raw["session.remove"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_6Request = Parameters<RawClient["server.session"]["session.switchAgent"]>[0]
type Endpoint3_6Input = {
  readonly sessionID: Endpoint3_6Request["params"]["sessionID"]
  readonly agent: Endpoint3_6Request["payload"]["agent"]
}
const Endpoint3_6 = (raw: RawClient["server.session"]) => (input: Endpoint3_6Input) =>
  raw["session.switchAgent"]({ params: { sessionID: input["sessionID"] }, payload: { agent: input["agent"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_7Request = Parameters<RawClient["server.session"]["session.switchModel"]>[0]
type Endpoint3_7Input = {
  readonly sessionID: Endpoint3_7Request["params"]["sessionID"]
  readonly model: Endpoint3_7Request["payload"]["model"]
}
const Endpoint3_7 = (raw: RawClient["server.session"]) => (input: Endpoint3_7Input) =>
  raw["session.switchModel"]({ params: { sessionID: input["sessionID"] }, payload: { model: input["model"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_8Request = Parameters<RawClient["server.session"]["session.prompt"]>[0]
type Endpoint3_8Input = {
  readonly sessionID: Endpoint3_8Request["params"]["sessionID"]
  readonly id?: Endpoint3_8Request["payload"]["id"]
  readonly prompt: Endpoint3_8Request["payload"]["prompt"]
  readonly delivery?: Endpoint3_8Request["payload"]["delivery"]
  readonly resume?: Endpoint3_8Request["payload"]["resume"]
}
const Endpoint3_8 = (raw: RawClient["server.session"]) => (input: Endpoint3_8Input) =>
  raw["session.prompt"]({
    params: { sessionID: input["sessionID"] },
    payload: { id: input["id"], prompt: input["prompt"], delivery: input["delivery"], resume: input["resume"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_9Request = Parameters<RawClient["server.session"]["session.externalTurn"]>[0]
type Endpoint3_9Input = {
  readonly sessionID: Endpoint3_9Request["params"]["sessionID"]
  readonly idempotencyKey: Endpoint3_9Request["payload"]["idempotencyKey"]
  readonly userText: Endpoint3_9Request["payload"]["userText"]
  readonly assistantText: Endpoint3_9Request["payload"]["assistantText"]
  readonly model?: Endpoint3_9Request["payload"]["model"]
}
const Endpoint3_9 = (raw: RawClient["server.session"]) => (input: Endpoint3_9Input) =>
  raw["session.externalTurn"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      idempotencyKey: input["idempotencyKey"],
      userText: input["userText"],
      assistantText: input["assistantText"],
      model: input["model"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_10Request = Parameters<RawClient["server.session"]["session.compact"]>[0]
type Endpoint3_10Input = { readonly sessionID: Endpoint3_10Request["params"]["sessionID"] }
const Endpoint3_10 = (raw: RawClient["server.session"]) => (input: Endpoint3_10Input) =>
  raw["session.compact"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_11Request = Parameters<RawClient["server.session"]["session.wait"]>[0]
type Endpoint3_11Input = { readonly sessionID: Endpoint3_11Request["params"]["sessionID"] }
const Endpoint3_11 = (raw: RawClient["server.session"]) => (input: Endpoint3_11Input) =>
  raw["session.wait"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_12Request = Parameters<RawClient["server.session"]["session.revert.stage"]>[0]
type Endpoint3_12Input = {
  readonly sessionID: Endpoint3_12Request["params"]["sessionID"]
  readonly messageID: Endpoint3_12Request["payload"]["messageID"]
  readonly files?: Endpoint3_12Request["payload"]["files"]
}
const Endpoint3_12 = (raw: RawClient["server.session"]) => (input: Endpoint3_12Input) =>
  raw["session.revert.stage"]({
    params: { sessionID: input["sessionID"] },
    payload: { messageID: input["messageID"], files: input["files"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_13Request = Parameters<RawClient["server.session"]["session.revert.clear"]>[0]
type Endpoint3_13Input = { readonly sessionID: Endpoint3_13Request["params"]["sessionID"] }
const Endpoint3_13 = (raw: RawClient["server.session"]) => (input: Endpoint3_13Input) =>
  raw["session.revert.clear"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_14Request = Parameters<RawClient["server.session"]["session.revert.commit"]>[0]
type Endpoint3_14Input = { readonly sessionID: Endpoint3_14Request["params"]["sessionID"] }
const Endpoint3_14 = (raw: RawClient["server.session"]) => (input: Endpoint3_14Input) =>
  raw["session.revert.commit"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_15Request = Parameters<RawClient["server.session"]["session.context"]>[0]
type Endpoint3_15Input = { readonly sessionID: Endpoint3_15Request["params"]["sessionID"] }
const Endpoint3_15 = (raw: RawClient["server.session"]) => (input: Endpoint3_15Input) =>
  raw["session.context"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_16Request = Parameters<RawClient["server.session"]["session.history"]>[0]
type Endpoint3_16Input = {
  readonly sessionID: Endpoint3_16Request["params"]["sessionID"]
  readonly limit?: Endpoint3_16Request["query"]["limit"]
  readonly after?: Endpoint3_16Request["query"]["after"]
}
const Endpoint3_16 = (raw: RawClient["server.session"]) => (input: Endpoint3_16Input) =>
  raw["session.history"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], after: input["after"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_17Request = Parameters<RawClient["server.session"]["session.events"]>[0]
type Endpoint3_17Input = {
  readonly sessionID: Endpoint3_17Request["params"]["sessionID"]
  readonly after?: Endpoint3_17Request["query"]["after"]
}
const Endpoint3_17 = (raw: RawClient["server.session"]) => (input: Endpoint3_17Input) =>
  Stream.unwrap(
    raw["session.events"]({ params: { sessionID: input["sessionID"] }, query: { after: input["after"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

type Endpoint3_18Request = Parameters<RawClient["server.session"]["session.interrupt"]>[0]
type Endpoint3_18Input = { readonly sessionID: Endpoint3_18Request["params"]["sessionID"] }
const Endpoint3_18 = (raw: RawClient["server.session"]) => (input: Endpoint3_18Input) =>
  raw["session.interrupt"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_19Request = Parameters<RawClient["server.session"]["session.message"]>[0]
type Endpoint3_19Input = {
  readonly sessionID: Endpoint3_19Request["params"]["sessionID"]
  readonly messageID: Endpoint3_19Request["params"]["messageID"]
}
const Endpoint3_19 = (raw: RawClient["server.session"]) => (input: Endpoint3_19Input) =>
  raw["session.message"]({ params: { sessionID: input["sessionID"], messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup3 = (raw: RawClient["server.session"]) => ({
  list: Endpoint3_0(raw),
  create: Endpoint3_1(raw),
  active: Endpoint3_2(raw),
  get: Endpoint3_3(raw),
  updateJarvis: Endpoint3_4(raw),
  remove: Endpoint3_5(raw),
  switchAgent: Endpoint3_6(raw),
  switchModel: Endpoint3_7(raw),
  prompt: Endpoint3_8(raw),
  externalTurn: Endpoint3_9(raw),
  compact: Endpoint3_10(raw),
  wait: Endpoint3_11(raw),
  stage: Endpoint3_12(raw),
  clear: Endpoint3_13(raw),
  commit: Endpoint3_14(raw),
  context: Endpoint3_15(raw),
  history: Endpoint3_16(raw),
  events: Endpoint3_17(raw),
  interrupt: Endpoint3_18(raw),
  message: Endpoint3_19(raw),
})

type Endpoint4_0Request = Parameters<RawClient["server.message"]["session.messages"]>[0]
type Endpoint4_0Input = {
  readonly sessionID: Endpoint4_0Request["params"]["sessionID"]
  readonly limit?: Endpoint4_0Request["query"]["limit"]
  readonly order?: Endpoint4_0Request["query"]["order"]
  readonly cursor?: Endpoint4_0Request["query"]["cursor"]
}
const Endpoint4_0 = (raw: RawClient["server.message"]) => (input: Endpoint4_0Input) =>
  raw["session.messages"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], order: input["order"], cursor: input["cursor"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup4 = (raw: RawClient["server.message"]) => ({ list: Endpoint4_0(raw) })

type Endpoint5_0Request = Parameters<RawClient["server.model"]["model.list"]>[0]
type Endpoint5_0Input = { readonly location?: Endpoint5_0Request["query"]["location"] }
const Endpoint5_0 = (raw: RawClient["server.model"]) => (input?: Endpoint5_0Input) =>
  raw["model.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup5 = (raw: RawClient["server.model"]) => ({ list: Endpoint5_0(raw) })

type Endpoint6_0Request = Parameters<RawClient["server.provider"]["provider.list"]>[0]
type Endpoint6_0Input = { readonly location?: Endpoint6_0Request["query"]["location"] }
const Endpoint6_0 = (raw: RawClient["server.provider"]) => (input?: Endpoint6_0Input) =>
  raw["provider.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint6_1Request = Parameters<RawClient["server.provider"]["provider.get"]>[0]
type Endpoint6_1Input = {
  readonly providerID: Endpoint6_1Request["params"]["providerID"]
  readonly location?: Endpoint6_1Request["query"]["location"]
}
const Endpoint6_1 = (raw: RawClient["server.provider"]) => (input: Endpoint6_1Input) =>
  raw["provider.get"]({ params: { providerID: input["providerID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup6 = (raw: RawClient["server.provider"]) => ({ list: Endpoint6_0(raw), get: Endpoint6_1(raw) })

type Endpoint7_0Request = Parameters<RawClient["server.integration"]["integration.list"]>[0]
type Endpoint7_0Input = { readonly location?: Endpoint7_0Request["query"]["location"] }
const Endpoint7_0 = (raw: RawClient["server.integration"]) => (input?: Endpoint7_0Input) =>
  raw["integration.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint7_1Request = Parameters<RawClient["server.integration"]["integration.get"]>[0]
type Endpoint7_1Input = {
  readonly integrationID: Endpoint7_1Request["params"]["integrationID"]
  readonly location?: Endpoint7_1Request["query"]["location"]
}
const Endpoint7_1 = (raw: RawClient["server.integration"]) => (input: Endpoint7_1Input) =>
  raw["integration.get"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_2Request = Parameters<RawClient["server.integration"]["integration.connect.key"]>[0]
type Endpoint7_2Input = {
  readonly integrationID: Endpoint7_2Request["params"]["integrationID"]
  readonly location?: Endpoint7_2Request["query"]["location"]
  readonly key: Endpoint7_2Request["payload"]["key"]
  readonly label?: Endpoint7_2Request["payload"]["label"]
}
const Endpoint7_2 = (raw: RawClient["server.integration"]) => (input: Endpoint7_2Input) =>
  raw["integration.connect.key"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { key: input["key"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_3Request = Parameters<RawClient["server.integration"]["integration.connect.oauth"]>[0]
type Endpoint7_3Input = {
  readonly integrationID: Endpoint7_3Request["params"]["integrationID"]
  readonly location?: Endpoint7_3Request["query"]["location"]
  readonly methodID: Endpoint7_3Request["payload"]["methodID"]
  readonly inputs: Endpoint7_3Request["payload"]["inputs"]
  readonly label?: Endpoint7_3Request["payload"]["label"]
}
const Endpoint7_3 = (raw: RawClient["server.integration"]) => (input: Endpoint7_3Input) =>
  raw["integration.connect.oauth"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { methodID: input["methodID"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_4Request = Parameters<RawClient["server.integration"]["integration.attempt.status"]>[0]
type Endpoint7_4Input = {
  readonly attemptID: Endpoint7_4Request["params"]["attemptID"]
  readonly location?: Endpoint7_4Request["query"]["location"]
}
const Endpoint7_4 = (raw: RawClient["server.integration"]) => (input: Endpoint7_4Input) =>
  raw["integration.attempt.status"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_5Request = Parameters<RawClient["server.integration"]["integration.attempt.complete"]>[0]
type Endpoint7_5Input = {
  readonly attemptID: Endpoint7_5Request["params"]["attemptID"]
  readonly location?: Endpoint7_5Request["query"]["location"]
  readonly code?: Endpoint7_5Request["payload"]["code"]
}
const Endpoint7_5 = (raw: RawClient["server.integration"]) => (input: Endpoint7_5Input) =>
  raw["integration.attempt.complete"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
    payload: { code: input["code"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_6Request = Parameters<RawClient["server.integration"]["integration.attempt.cancel"]>[0]
type Endpoint7_6Input = {
  readonly attemptID: Endpoint7_6Request["params"]["attemptID"]
  readonly location?: Endpoint7_6Request["query"]["location"]
}
const Endpoint7_6 = (raw: RawClient["server.integration"]) => (input: Endpoint7_6Input) =>
  raw["integration.attempt.cancel"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup7 = (raw: RawClient["server.integration"]) => ({
  list: Endpoint7_0(raw),
  get: Endpoint7_1(raw),
  connectKey: Endpoint7_2(raw),
  connectOauth: Endpoint7_3(raw),
  attemptStatus: Endpoint7_4(raw),
  attemptComplete: Endpoint7_5(raw),
  attemptCancel: Endpoint7_6(raw),
})

type Endpoint8_0Request = Parameters<RawClient["server.credential"]["credential.update"]>[0]
type Endpoint8_0Input = {
  readonly credentialID: Endpoint8_0Request["params"]["credentialID"]
  readonly location?: Endpoint8_0Request["query"]["location"]
  readonly label: Endpoint8_0Request["payload"]["label"]
}
const Endpoint8_0 = (raw: RawClient["server.credential"]) => (input: Endpoint8_0Input) =>
  raw["credential.update"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
    payload: { label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_1Request = Parameters<RawClient["server.credential"]["credential.remove"]>[0]
type Endpoint8_1Input = {
  readonly credentialID: Endpoint8_1Request["params"]["credentialID"]
  readonly location?: Endpoint8_1Request["query"]["location"]
}
const Endpoint8_1 = (raw: RawClient["server.credential"]) => (input: Endpoint8_1Input) =>
  raw["credential.remove"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup8 = (raw: RawClient["server.credential"]) => ({ update: Endpoint8_0(raw), remove: Endpoint8_1(raw) })

type Endpoint9_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
type Endpoint9_0Input = { readonly location?: Endpoint9_0Request["query"]["location"] }
const Endpoint9_0 = (raw: RawClient["server.permission"]) => (input?: Endpoint9_0Input) =>
  raw["permission.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint9_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
type Endpoint9_1Input = { readonly projectID?: Endpoint9_1Request["query"]["projectID"] }
const Endpoint9_1 = (raw: RawClient["server.permission"]) => (input?: Endpoint9_1Input) =>
  raw["permission.saved.list"]({ query: { projectID: input?.["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint9_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
type Endpoint9_2Input = { readonly id: Endpoint9_2Request["params"]["id"] }
const Endpoint9_2 = (raw: RawClient["server.permission"]) => (input: Endpoint9_2Input) =>
  raw["permission.saved.remove"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint9_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
type Endpoint9_3Input = {
  readonly sessionID: Endpoint9_3Request["params"]["sessionID"]
  readonly id?: Endpoint9_3Request["payload"]["id"]
  readonly action: Endpoint9_3Request["payload"]["action"]
  readonly resources: Endpoint9_3Request["payload"]["resources"]
  readonly save?: Endpoint9_3Request["payload"]["save"]
  readonly metadata?: Endpoint9_3Request["payload"]["metadata"]
  readonly source?: Endpoint9_3Request["payload"]["source"]
  readonly agent?: Endpoint9_3Request["payload"]["agent"]
}
const Endpoint9_3 = (raw: RawClient["server.permission"]) => (input: Endpoint9_3Input) =>
  raw["session.permission.create"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      action: input["action"],
      resources: input["resources"],
      save: input["save"],
      metadata: input["metadata"],
      source: input["source"],
      agent: input["agent"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint9_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
type Endpoint9_4Input = { readonly sessionID: Endpoint9_4Request["params"]["sessionID"] }
const Endpoint9_4 = (raw: RawClient["server.permission"]) => (input: Endpoint9_4Input) =>
  raw["session.permission.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint9_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
type Endpoint9_5Input = {
  readonly sessionID: Endpoint9_5Request["params"]["sessionID"]
  readonly requestID: Endpoint9_5Request["params"]["requestID"]
}
const Endpoint9_5 = (raw: RawClient["server.permission"]) => (input: Endpoint9_5Input) =>
  raw["session.permission.get"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint9_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
type Endpoint9_6Input = {
  readonly sessionID: Endpoint9_6Request["params"]["sessionID"]
  readonly requestID: Endpoint9_6Request["params"]["requestID"]
  readonly reply: Endpoint9_6Request["payload"]["reply"]
  readonly message?: Endpoint9_6Request["payload"]["message"]
}
const Endpoint9_6 = (raw: RawClient["server.permission"]) => (input: Endpoint9_6Input) =>
  raw["session.permission.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { reply: input["reply"], message: input["message"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup9 = (raw: RawClient["server.permission"]) => ({
  listRequests: Endpoint9_0(raw),
  listSaved: Endpoint9_1(raw),
  removeSaved: Endpoint9_2(raw),
  create: Endpoint9_3(raw),
  list: Endpoint9_4(raw),
  get: Endpoint9_5(raw),
  reply: Endpoint9_6(raw),
})

type Endpoint10_0Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
type Endpoint10_0Input = {
  readonly location?: Endpoint10_0Request["query"]["location"]
  readonly path?: Endpoint10_0Request["query"]["path"]
}
const Endpoint10_0 = (raw: RawClient["server.fs"]) => (input?: Endpoint10_0Input) =>
  raw["fs.list"]({ query: { location: input?.["location"], path: input?.["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint10_1Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
type Endpoint10_1Input = {
  readonly location?: Endpoint10_1Request["query"]["location"]
  readonly query: Endpoint10_1Request["query"]["query"]
  readonly type?: Endpoint10_1Request["query"]["type"]
  readonly limit?: Endpoint10_1Request["query"]["limit"]
}
const Endpoint10_1 = (raw: RawClient["server.fs"]) => (input: Endpoint10_1Input) =>
  raw["fs.find"]({
    query: { location: input["location"], query: input["query"], type: input["type"], limit: input["limit"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup10 = (raw: RawClient["server.fs"]) => ({ list: Endpoint10_0(raw), find: Endpoint10_1(raw) })

type Endpoint11_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
type Endpoint11_0Input = { readonly location?: Endpoint11_0Request["query"]["location"] }
const Endpoint11_0 = (raw: RawClient["server.command"]) => (input?: Endpoint11_0Input) =>
  raw["command.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup11 = (raw: RawClient["server.command"]) => ({ list: Endpoint11_0(raw) })

type Endpoint12_0Request = Parameters<RawClient["server.skill"]["skill.list"]>[0]
type Endpoint12_0Input = { readonly location?: Endpoint12_0Request["query"]["location"] }
const Endpoint12_0 = (raw: RawClient["server.skill"]) => (input?: Endpoint12_0Input) =>
  raw["skill.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup12 = (raw: RawClient["server.skill"]) => ({ list: Endpoint12_0(raw) })

const Endpoint13_0 = (raw: RawClient["server.event"]) => () =>
  Stream.unwrap(
    raw["event.subscribe"]({}).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup13 = (raw: RawClient["server.event"]) => ({ subscribe: Endpoint13_0(raw) })

type Endpoint14_0Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
type Endpoint14_0Input = { readonly location?: Endpoint14_0Request["query"]["location"] }
const Endpoint14_0 = (raw: RawClient["server.pty"]) => (input?: Endpoint14_0Input) =>
  raw["pty.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint14_1Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
type Endpoint14_1Input = {
  readonly location?: Endpoint14_1Request["query"]["location"]
  readonly command?: Endpoint14_1Request["payload"]["command"]
  readonly args?: Endpoint14_1Request["payload"]["args"]
  readonly cwd?: Endpoint14_1Request["payload"]["cwd"]
  readonly title?: Endpoint14_1Request["payload"]["title"]
  readonly env?: Endpoint14_1Request["payload"]["env"]
}
const Endpoint14_1 = (raw: RawClient["server.pty"]) => (input?: Endpoint14_1Input) =>
  raw["pty.create"]({
    query: { location: input?.["location"] },
    payload: {
      command: input?.["command"],
      args: input?.["args"],
      cwd: input?.["cwd"],
      title: input?.["title"],
      env: input?.["env"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint14_2Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
type Endpoint14_2Input = {
  readonly ptyID: Endpoint14_2Request["params"]["ptyID"]
  readonly location?: Endpoint14_2Request["query"]["location"]
}
const Endpoint14_2 = (raw: RawClient["server.pty"]) => (input: Endpoint14_2Input) =>
  raw["pty.get"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint14_3Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
type Endpoint14_3Input = {
  readonly ptyID: Endpoint14_3Request["params"]["ptyID"]
  readonly location?: Endpoint14_3Request["query"]["location"]
  readonly title?: Endpoint14_3Request["payload"]["title"]
  readonly size?: Endpoint14_3Request["payload"]["size"]
}
const Endpoint14_3 = (raw: RawClient["server.pty"]) => (input: Endpoint14_3Input) =>
  raw["pty.update"]({
    params: { ptyID: input["ptyID"] },
    query: { location: input["location"] },
    payload: { title: input["title"], size: input["size"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint14_4Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
type Endpoint14_4Input = {
  readonly ptyID: Endpoint14_4Request["params"]["ptyID"]
  readonly location?: Endpoint14_4Request["query"]["location"]
}
const Endpoint14_4 = (raw: RawClient["server.pty"]) => (input: Endpoint14_4Input) =>
  raw["pty.remove"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup14 = (raw: RawClient["server.pty"]) => ({
  list: Endpoint14_0(raw),
  create: Endpoint14_1(raw),
  get: Endpoint14_2(raw),
  update: Endpoint14_3(raw),
  remove: Endpoint14_4(raw),
})

type Endpoint15_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
type Endpoint15_0Input = { readonly location?: Endpoint15_0Request["query"]["location"] }
const Endpoint15_0 = (raw: RawClient["server.question"]) => (input?: Endpoint15_0Input) =>
  raw["question.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint15_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
type Endpoint15_1Input = { readonly sessionID: Endpoint15_1Request["params"]["sessionID"] }
const Endpoint15_1 = (raw: RawClient["server.question"]) => (input: Endpoint15_1Input) =>
  raw["session.question.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint15_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
type Endpoint15_2Input = {
  readonly sessionID: Endpoint15_2Request["params"]["sessionID"]
  readonly requestID: Endpoint15_2Request["params"]["requestID"]
  readonly answers: Endpoint15_2Request["payload"]["answers"]
}
const Endpoint15_2 = (raw: RawClient["server.question"]) => (input: Endpoint15_2Input) =>
  raw["session.question.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { answers: input["answers"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint15_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
type Endpoint15_3Input = {
  readonly sessionID: Endpoint15_3Request["params"]["sessionID"]
  readonly requestID: Endpoint15_3Request["params"]["requestID"]
}
const Endpoint15_3 = (raw: RawClient["server.question"]) => (input: Endpoint15_3Input) =>
  raw["session.question.reject"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup15 = (raw: RawClient["server.question"]) => ({
  listRequests: Endpoint15_0(raw),
  list: Endpoint15_1(raw),
  reply: Endpoint15_2(raw),
  reject: Endpoint15_3(raw),
})

type Endpoint16_0Request = Parameters<RawClient["server.reference"]["reference.list"]>[0]
type Endpoint16_0Input = { readonly location?: Endpoint16_0Request["query"]["location"] }
const Endpoint16_0 = (raw: RawClient["server.reference"]) => (input?: Endpoint16_0Input) =>
  raw["reference.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup16 = (raw: RawClient["server.reference"]) => ({ list: Endpoint16_0(raw) })

type Endpoint17_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
type Endpoint17_0Input = {
  readonly projectID: Endpoint17_0Request["params"]["projectID"]
  readonly location?: Endpoint17_0Request["query"]["location"]
  readonly strategy: Endpoint17_0Request["payload"]["strategy"]
  readonly directory: Endpoint17_0Request["payload"]["directory"]
  readonly name?: Endpoint17_0Request["payload"]["name"]
}
const Endpoint17_0 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint17_0Input) =>
  raw["projectCopy.create"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { strategy: input["strategy"], directory: input["directory"], name: input["name"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint17_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
type Endpoint17_1Input = {
  readonly projectID: Endpoint17_1Request["params"]["projectID"]
  readonly location?: Endpoint17_1Request["query"]["location"]
  readonly directory: Endpoint17_1Request["payload"]["directory"]
  readonly force: Endpoint17_1Request["payload"]["force"]
}
const Endpoint17_1 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint17_1Input) =>
  raw["projectCopy.remove"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { directory: input["directory"], force: input["force"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint17_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
type Endpoint17_2Input = {
  readonly projectID: Endpoint17_2Request["params"]["projectID"]
  readonly location?: Endpoint17_2Request["query"]["location"]
}
const Endpoint17_2 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint17_2Input) =>
  raw["projectCopy.refresh"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup17 = (raw: RawClient["server.projectCopy"]) => ({
  create: Endpoint17_0(raw),
  remove: Endpoint17_1(raw),
  refresh: Endpoint17_2(raw),
})

type Endpoint18_0Request = Parameters<RawClient["server.repositoryMap"]["repositoryMap.get"]>[0]
type Endpoint18_0Input = { readonly location?: Endpoint18_0Request["query"]["location"] }
const Endpoint18_0 = (raw: RawClient["server.repositoryMap"]) => (input?: Endpoint18_0Input) =>
  raw["repositoryMap.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint18_1Request = Parameters<RawClient["server.repositoryMap"]["repositoryMap.refresh"]>[0]
type Endpoint18_1Input = { readonly location?: Endpoint18_1Request["query"]["location"] }
const Endpoint18_1 = (raw: RawClient["server.repositoryMap"]) => (input?: Endpoint18_1Input) =>
  raw["repositoryMap.refresh"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint18_2Request = Parameters<RawClient["server.repositoryMap"]["repositoryMap.diagnostics"]>[0]
type Endpoint18_2Input = { readonly location?: Endpoint18_2Request["query"]["location"] }
const Endpoint18_2 = (raw: RawClient["server.repositoryMap"]) => (input?: Endpoint18_2Input) =>
  raw["repositoryMap.diagnostics"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint18_3Request = Parameters<RawClient["server.repositoryMap"]["repositoryMap.configureDiagnostics"]>[0]
type Endpoint18_3Input = {
  readonly location?: Endpoint18_3Request["query"]["location"]
  readonly enabled: Endpoint18_3Request["payload"]["enabled"]
  readonly clear?: Endpoint18_3Request["payload"]["clear"]
}
const Endpoint18_3 = (raw: RawClient["server.repositoryMap"]) => (input: Endpoint18_3Input) =>
  raw["repositoryMap.configureDiagnostics"]({
    query: { location: input["location"] },
    payload: { enabled: input["enabled"], clear: input["clear"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_4Request = Parameters<RawClient["server.repositoryMap"]["repositoryMap.knowledge"]>[0]
type Endpoint18_4Input = {
  readonly location?: Endpoint18_4Request["query"]["location"]
  readonly search?: Endpoint18_4Request["query"]["search"]
  readonly limit?: Endpoint18_4Request["query"]["limit"]
}
const Endpoint18_4 = (raw: RawClient["server.repositoryMap"]) => (input?: Endpoint18_4Input) =>
  raw["repositoryMap.knowledge"]({
    query: { location: input?.["location"], search: input?.["search"], limit: input?.["limit"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_5Request = Parameters<RawClient["server.repositoryMap"]["repositoryMap.removeKnowledge"]>[0]
type Endpoint18_5Input = {
  readonly scope: Endpoint18_5Request["params"]["scope"]
  readonly id: Endpoint18_5Request["params"]["id"]
  readonly location?: Endpoint18_5Request["query"]["location"]
}
const Endpoint18_5 = (raw: RawClient["server.repositoryMap"]) => (input: Endpoint18_5Input) =>
  raw["repositoryMap.removeKnowledge"]({
    params: { scope: input["scope"], id: input["id"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_6Request = Parameters<RawClient["server.repositoryMap"]["repositoryMap.updateMemory"]>[0]
type Endpoint18_6Input = {
  readonly id: Endpoint18_6Request["params"]["id"]
  readonly location?: Endpoint18_6Request["query"]["location"]
  readonly pinned?: Endpoint18_6Request["payload"]["pinned"]
  readonly expiresAt?: Endpoint18_6Request["payload"]["expiresAt"]
  readonly clearExpiration?: Endpoint18_6Request["payload"]["clearExpiration"]
  readonly resolve?: Endpoint18_6Request["payload"]["resolve"]
  readonly lifecycle?: Endpoint18_6Request["payload"]["lifecycle"]
}
const Endpoint18_6 = (raw: RawClient["server.repositoryMap"]) => (input: Endpoint18_6Input) =>
  raw["repositoryMap.updateMemory"]({
    params: { id: input["id"] },
    query: { location: input["location"] },
    payload: {
      pinned: input["pinned"],
      expiresAt: input["expiresAt"],
      clearExpiration: input["clearExpiration"],
      resolve: input["resolve"],
      lifecycle: input["lifecycle"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_7Request = Parameters<RawClient["server.repositoryMap"]["repositoryMap.previewMemoryConsolidation"]>[0]
type Endpoint18_7Input = { readonly location?: Endpoint18_7Request["query"]["location"] }
const Endpoint18_7 = (raw: RawClient["server.repositoryMap"]) => (input?: Endpoint18_7Input) =>
  raw["repositoryMap.previewMemoryConsolidation"]({ query: { location: input?.["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint18_8Request = Parameters<RawClient["server.repositoryMap"]["repositoryMap.applyMemoryConsolidation"]>[0]
type Endpoint18_8Input = {
  readonly location?: Endpoint18_8Request["query"]["location"]
  readonly fingerprint: Endpoint18_8Request["payload"]["fingerprint"]
  readonly generatedAt: Endpoint18_8Request["payload"]["generatedAt"]
}
const Endpoint18_8 = (raw: RawClient["server.repositoryMap"]) => (input: Endpoint18_8Input) =>
  raw["repositoryMap.applyMemoryConsolidation"]({
    query: { location: input["location"] },
    payload: { fingerprint: input["fingerprint"], generatedAt: input["generatedAt"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_9Request = Parameters<RawClient["server.repositoryMap"]["repositoryMap.feedbackRetrieval"]>[0]
type Endpoint18_9Input = {
  readonly id: Endpoint18_9Request["params"]["id"]
  readonly location?: Endpoint18_9Request["query"]["location"]
  readonly path: Endpoint18_9Request["payload"]["path"]
  readonly relevance: Endpoint18_9Request["payload"]["relevance"]
}
const Endpoint18_9 = (raw: RawClient["server.repositoryMap"]) => (input: Endpoint18_9Input) =>
  raw["repositoryMap.feedbackRetrieval"]({
    params: { id: input["id"] },
    query: { location: input["location"] },
    payload: { path: input["path"], relevance: input["relevance"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_10Request = Parameters<RawClient["server.repositoryMap"]["repositoryMap.clearKnowledge"]>[0]
type Endpoint18_10Input = {
  readonly scope: Endpoint18_10Request["params"]["scope"]
  readonly location?: Endpoint18_10Request["query"]["location"]
}
const Endpoint18_10 = (raw: RawClient["server.repositoryMap"]) => (input: Endpoint18_10Input) =>
  raw["repositoryMap.clearKnowledge"]({
    params: { scope: input["scope"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup18 = (raw: RawClient["server.repositoryMap"]) => ({
  get: Endpoint18_0(raw),
  refresh: Endpoint18_1(raw),
  diagnostics: Endpoint18_2(raw),
  configureDiagnostics: Endpoint18_3(raw),
  knowledge: Endpoint18_4(raw),
  removeKnowledge: Endpoint18_5(raw),
  updateMemory: Endpoint18_6(raw),
  previewMemoryConsolidation: Endpoint18_7(raw),
  applyMemoryConsolidation: Endpoint18_8(raw),
  feedbackRetrieval: Endpoint18_9(raw),
  clearKnowledge: Endpoint18_10(raw),
})

const Endpoint19_0 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.conversation"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint19_1Request = Parameters<RawClient["server.jarvis"]["jarvis.adoptConversation"]>[0]
type Endpoint19_1Input = {
  readonly sessionID?: Endpoint19_1Request["payload"]["sessionID"]
  readonly profileID?: Endpoint19_1Request["payload"]["profileID"]
  readonly profileRevision?: Endpoint19_1Request["payload"]["profileRevision"]
  readonly surface: Endpoint19_1Request["payload"]["surface"]
}
const Endpoint19_1 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_1Input) =>
  raw["jarvis.adoptConversation"]({
    payload: {
      sessionID: input["sessionID"],
      profileID: input["profileID"],
      profileRevision: input["profileRevision"],
      surface: input["surface"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_2Request = Parameters<RawClient["server.jarvis"]["jarvis.prewarm"]>[0]
type Endpoint19_2Input = {
  readonly turnID?: Endpoint19_2Request["payload"]["turnID"]
  readonly requestID: Endpoint19_2Request["payload"]["requestID"]
  readonly surface: Endpoint19_2Request["payload"]["surface"]
  readonly text: Endpoint19_2Request["payload"]["text"]
  readonly sequence: Endpoint19_2Request["payload"]["sequence"]
  readonly language?: Endpoint19_2Request["payload"]["language"]
  readonly profileRevision?: Endpoint19_2Request["payload"]["profileRevision"]
  readonly worldContext?: Endpoint19_2Request["payload"]["worldContext"]
  readonly capturedAt: Endpoint19_2Request["payload"]["capturedAt"]
}
const Endpoint19_2 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_2Input) =>
  raw["jarvis.prewarm"]({
    payload: {
      turnID: input["turnID"],
      requestID: input["requestID"],
      surface: input["surface"],
      text: input["text"],
      sequence: input["sequence"],
      language: input["language"],
      profileRevision: input["profileRevision"],
      worldContext: input["worldContext"],
      capturedAt: input["capturedAt"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_3Request = Parameters<RawClient["server.jarvis"]["jarvis.admitFinal"]>[0]
type Endpoint19_3Input = {
  readonly requestID: Endpoint19_3Request["payload"]["requestID"]
  readonly transcript: Endpoint19_3Request["payload"]["transcript"]
  readonly surface: Endpoint19_3Request["payload"]["surface"]
  readonly responseMode: Endpoint19_3Request["payload"]["responseMode"]
  readonly profileID?: Endpoint19_3Request["payload"]["profileID"]
  readonly profileRevision?: Endpoint19_3Request["payload"]["profileRevision"]
  readonly worldContext?: Endpoint19_3Request["payload"]["worldContext"]
}
const Endpoint19_3 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_3Input) =>
  raw["jarvis.admitFinal"]({
    payload: {
      requestID: input["requestID"],
      transcript: input["transcript"],
      surface: input["surface"],
      responseMode: input["responseMode"],
      profileID: input["profileID"],
      profileRevision: input["profileRevision"],
      worldContext: input["worldContext"],
    },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint19_4 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.controlStatus"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint19_5Request = Parameters<RawClient["server.jarvis"]["jarvis.updateMediaState"]>[0]
type Endpoint19_5Input = {
  readonly turnID?: Endpoint19_5Request["payload"]["turnID"]
  readonly owner?: Endpoint19_5Request["payload"]["owner"]
  readonly state: Endpoint19_5Request["payload"]["state"]
  readonly queuedSentences: Endpoint19_5Request["payload"]["queuedSentences"]
  readonly activeJobs: Endpoint19_5Request["payload"]["activeJobs"]
  readonly acknowledgedCancellation: Endpoint19_5Request["payload"]["acknowledgedCancellation"]
}
const Endpoint19_5 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_5Input) =>
  raw["jarvis.updateMediaState"]({
    payload: {
      turnID: input["turnID"],
      owner: input["owner"],
      state: input["state"],
      queuedSentences: input["queuedSentences"],
      activeJobs: input["activeJobs"],
      acknowledgedCancellation: input["acknowledgedCancellation"],
    },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint19_6 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.runDiagnostics"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint19_7Request = Parameters<RawClient["server.jarvis"]["jarvis.createTurn"]>[0]
type Endpoint19_7Input = {
  readonly requestID: Endpoint19_7Request["payload"]["requestID"]
  readonly sessionID: Endpoint19_7Request["payload"]["sessionID"]
  readonly profileID?: Endpoint19_7Request["payload"]["profileID"]
  readonly surface: Endpoint19_7Request["payload"]["surface"]
  readonly responseMode: Endpoint19_7Request["payload"]["responseMode"]
  readonly phase?: Endpoint19_7Request["payload"]["phase"]
}
const Endpoint19_7 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_7Input) =>
  raw["jarvis.createTurn"]({
    payload: {
      requestID: input["requestID"],
      sessionID: input["sessionID"],
      profileID: input["profileID"],
      surface: input["surface"],
      responseMode: input["responseMode"],
      phase: input["phase"],
    },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint19_8 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.currentTurn"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint19_9Request = Parameters<RawClient["server.jarvis"]["jarvis.turn"]>[0]
type Endpoint19_9Input = { readonly turnID: Endpoint19_9Request["params"]["turnID"] }
const Endpoint19_9 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_9Input) =>
  raw["jarvis.turn"]({ params: { turnID: input["turnID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_10Request = Parameters<RawClient["server.jarvis"]["jarvis.updateTurn"]>[0]
type Endpoint19_10Input = {
  readonly turnID: Endpoint19_10Request["params"]["turnID"]
  readonly phase: Endpoint19_10Request["payload"]["phase"]
  readonly sequence: Endpoint19_10Request["payload"]["sequence"]
  readonly presentation?: Endpoint19_10Request["payload"]["presentation"]
  readonly metrics?: Endpoint19_10Request["payload"]["metrics"]
  readonly error?: Endpoint19_10Request["payload"]["error"]
  readonly cancelReason?: Endpoint19_10Request["payload"]["cancelReason"]
}
const Endpoint19_10 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_10Input) =>
  raw["jarvis.updateTurn"]({
    params: { turnID: input["turnID"] },
    payload: {
      phase: input["phase"],
      sequence: input["sequence"],
      presentation: input["presentation"],
      metrics: input["metrics"],
      error: input["error"],
      cancelReason: input["cancelReason"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_11Request = Parameters<RawClient["server.jarvis"]["jarvis.cancelTurn"]>[0]
type Endpoint19_11Input = {
  readonly turnID: Endpoint19_11Request["params"]["turnID"]
  readonly reason?: Endpoint19_11Request["payload"]["reason"]
}
const Endpoint19_11 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_11Input) =>
  raw["jarvis.cancelTurn"]({ params: { turnID: input["turnID"] }, payload: { reason: input["reason"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const Endpoint19_12 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.presence"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint19_13Request = Parameters<RawClient["server.jarvis"]["jarvis.handoffPresence"]>[0]
type Endpoint19_13Input = {
  readonly from?: Endpoint19_13Request["payload"]["from"]
  readonly to: Endpoint19_13Request["payload"]["to"]
  readonly sessionID?: Endpoint19_13Request["payload"]["sessionID"]
  readonly turnID?: Endpoint19_13Request["payload"]["turnID"]
  readonly microphone: Endpoint19_13Request["payload"]["microphone"]
  readonly playback: Endpoint19_13Request["payload"]["playback"]
}
const Endpoint19_13 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_13Input) =>
  raw["jarvis.handoffPresence"]({
    payload: {
      from: input["from"],
      to: input["to"],
      sessionID: input["sessionID"],
      turnID: input["turnID"],
      microphone: input["microphone"],
      playback: input["playback"],
    },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint19_14 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.status"]({}).pipe(Effect.mapError(mapClientError))

const Endpoint19_15 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.config"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint19_16Request = Parameters<RawClient["server.jarvis"]["jarvis.updateConfig"]>[0]
type Endpoint19_16Input = {
  readonly primaryProfileID?: Endpoint19_16Request["payload"]["primaryProfileID"]
  readonly inboxSessionID?: Endpoint19_16Request["payload"]["inboxSessionID"]
  readonly models: Endpoint19_16Request["payload"]["models"]
  readonly plannerTimeoutMs: Endpoint19_16Request["payload"]["plannerTimeoutMs"]
  readonly plannerIdleUnloadMs: Endpoint19_16Request["payload"]["plannerIdleUnloadMs"]
  readonly plannerEscalationMinWords: Endpoint19_16Request["payload"]["plannerEscalationMinWords"]
  readonly reactor: Endpoint19_16Request["payload"]["reactor"]
  readonly benchmark: Endpoint19_16Request["payload"]["benchmark"]
  readonly initiative: Endpoint19_16Request["payload"]["initiative"]
  readonly updatedAt: Endpoint19_16Request["payload"]["updatedAt"]
}
const Endpoint19_16 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_16Input) =>
  raw["jarvis.updateConfig"]({
    payload: {
      primaryProfileID: input["primaryProfileID"],
      inboxSessionID: input["inboxSessionID"],
      models: input["models"],
      plannerTimeoutMs: input["plannerTimeoutMs"],
      plannerIdleUnloadMs: input["plannerIdleUnloadMs"],
      plannerEscalationMinWords: input["plannerEscalationMinWords"],
      reactor: input["reactor"],
      benchmark: input["benchmark"],
      initiative: input["initiative"],
      updatedAt: input["updatedAt"],
    },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint19_17 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.benchmarkStatus"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint19_18Request = Parameters<RawClient["server.jarvis"]["jarvis.runBenchmark"]>[0]
type Endpoint19_18Input = { readonly profile: Endpoint19_18Request["payload"]["profile"] }
const Endpoint19_18 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_18Input) =>
  raw["jarvis.runBenchmark"]({ payload: { profile: input["profile"] } }).pipe(Effect.mapError(mapClientError))

const Endpoint19_19 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.cancelBenchmark"]({}).pipe(Effect.mapError(mapClientError))

const Endpoint19_20 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.profiles"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint19_21Request = Parameters<RawClient["server.jarvis"]["jarvis.syncProfiles"]>[0]
type Endpoint19_21Input = {
  readonly profiles: Endpoint19_21Request["payload"]["profiles"]
  readonly primaryProfileID?: Endpoint19_21Request["payload"]["primaryProfileID"]
}
const Endpoint19_21 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_21Input) =>
  raw["jarvis.syncProfiles"]({
    payload: { profiles: input["profiles"], primaryProfileID: input["primaryProfileID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_22Request = Parameters<RawClient["server.jarvis"]["jarvis.goals"]>[0]
type Endpoint19_22Input = { readonly status?: Endpoint19_22Request["query"]["status"] }
const Endpoint19_22 = (raw: RawClient["server.jarvis"]) => (input?: Endpoint19_22Input) =>
  raw["jarvis.goals"]({ query: { status: input?.["status"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_23Request = Parameters<RawClient["server.jarvis"]["jarvis.createGoal"]>[0]
type Endpoint19_23Input = {
  readonly profileID: Endpoint19_23Request["payload"]["profileID"]
  readonly sessionID?: Endpoint19_23Request["payload"]["sessionID"]
  readonly mode: Endpoint19_23Request["payload"]["mode"]
  readonly gameID?: Endpoint19_23Request["payload"]["gameID"]
  readonly saveSlotID?: Endpoint19_23Request["payload"]["saveSlotID"]
  readonly characterID?: Endpoint19_23Request["payload"]["characterID"]
  readonly objective: Endpoint19_23Request["payload"]["objective"]
  readonly worldRevision?: Endpoint19_23Request["payload"]["worldRevision"]
  readonly capabilityRevision?: Endpoint19_23Request["payload"]["capabilityRevision"]
}
const Endpoint19_23 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_23Input) =>
  raw["jarvis.createGoal"]({
    payload: {
      profileID: input["profileID"],
      sessionID: input["sessionID"],
      mode: input["mode"],
      gameID: input["gameID"],
      saveSlotID: input["saveSlotID"],
      characterID: input["characterID"],
      objective: input["objective"],
      worldRevision: input["worldRevision"],
      capabilityRevision: input["capabilityRevision"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_24Request = Parameters<RawClient["server.jarvis"]["jarvis.resumeGoal"]>[0]
type Endpoint19_24Input = {
  readonly goalID: Endpoint19_24Request["params"]["goalID"]
  readonly worldRevision: Endpoint19_24Request["payload"]["worldRevision"]
  readonly capabilityRevision: Endpoint19_24Request["payload"]["capabilityRevision"]
  readonly gameID?: Endpoint19_24Request["payload"]["gameID"]
  readonly saveSlotID?: Endpoint19_24Request["payload"]["saveSlotID"]
  readonly characterID?: Endpoint19_24Request["payload"]["characterID"]
}
const Endpoint19_24 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_24Input) =>
  raw["jarvis.resumeGoal"]({
    params: { goalID: input["goalID"] },
    payload: {
      worldRevision: input["worldRevision"],
      capabilityRevision: input["capabilityRevision"],
      gameID: input["gameID"],
      saveSlotID: input["saveSlotID"],
      characterID: input["characterID"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_25Request = Parameters<RawClient["server.jarvis"]["jarvis.replanGoal"]>[0]
type Endpoint19_25Input = {
  readonly goalID: Endpoint19_25Request["params"]["goalID"]
  readonly reason?: Endpoint19_25Request["payload"]["reason"]
}
const Endpoint19_25 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_25Input) =>
  raw["jarvis.replanGoal"]({ params: { goalID: input["goalID"] }, payload: { reason: input["reason"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint19_26Request = Parameters<RawClient["server.jarvis"]["jarvis.cancelGoal"]>[0]
type Endpoint19_26Input = {
  readonly goalID: Endpoint19_26Request["params"]["goalID"]
  readonly summary?: Endpoint19_26Request["payload"]["summary"]
  readonly changedEntityIDs?: Endpoint19_26Request["payload"]["changedEntityIDs"]
}
const Endpoint19_26 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_26Input) =>
  raw["jarvis.cancelGoal"]({
    params: { goalID: input["goalID"] },
    payload: { summary: input["summary"], changedEntityIDs: input["changedEntityIDs"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_27Request = Parameters<RawClient["server.jarvis"]["jarvis.recordGoalStep"]>[0]
type Endpoint19_27Input = {
  readonly goalID: Endpoint19_27Request["params"]["goalID"]
  readonly stepID: Endpoint19_27Request["payload"]["stepID"]
  readonly success: Endpoint19_27Request["payload"]["success"]
  readonly error?: Endpoint19_27Request["payload"]["error"]
}
const Endpoint19_27 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_27Input) =>
  raw["jarvis.recordGoalStep"]({
    params: { goalID: input["goalID"] },
    payload: { stepID: input["stepID"], success: input["success"], error: input["error"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_28Request = Parameters<RawClient["server.jarvis"]["jarvis.outcomes"]>[0]
type Endpoint19_28Input = { readonly goalID?: Endpoint19_28Request["query"]["goalID"] }
const Endpoint19_28 = (raw: RawClient["server.jarvis"]) => (input?: Endpoint19_28Input) =>
  raw["jarvis.outcomes"]({ query: { goalID: input?.["goalID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_29Request = Parameters<RawClient["server.jarvis"]["jarvis.completeGoal"]>[0]
type Endpoint19_29Input = {
  readonly goalID: Endpoint19_29Request["params"]["goalID"]
  readonly status: Endpoint19_29Request["payload"]["status"]
  readonly summary: Endpoint19_29Request["payload"]["summary"]
  readonly changedEntityIDs: Endpoint19_29Request["payload"]["changedEntityIDs"]
}
const Endpoint19_29 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_29Input) =>
  raw["jarvis.completeGoal"]({
    params: { goalID: input["goalID"] },
    payload: { status: input["status"], summary: input["summary"], changedEntityIDs: input["changedEntityIDs"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_30Request = Parameters<RawClient["server.jarvis"]["jarvis.searchMemory"]>[0]
type Endpoint19_30Input = {
  readonly query: Endpoint19_30Request["payload"]["query"]
  readonly profileID?: Endpoint19_30Request["payload"]["profileID"]
  readonly gameID?: Endpoint19_30Request["payload"]["gameID"]
  readonly saveSlotID?: Endpoint19_30Request["payload"]["saveSlotID"]
  readonly characterID?: Endpoint19_30Request["payload"]["characterID"]
  readonly limit?: Endpoint19_30Request["payload"]["limit"]
  readonly embedding?: Endpoint19_30Request["payload"]["embedding"]
}
const Endpoint19_30 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_30Input) =>
  raw["jarvis.searchMemory"]({
    payload: {
      query: input["query"],
      profileID: input["profileID"],
      gameID: input["gameID"],
      saveSlotID: input["saveSlotID"],
      characterID: input["characterID"],
      limit: input["limit"],
      embedding: input["embedding"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_31Request = Parameters<RawClient["server.jarvis"]["jarvis.remember"]>[0]
type Endpoint19_31Input = {
  readonly id: Endpoint19_31Request["payload"]["id"]
  readonly profileID?: Endpoint19_31Request["payload"]["profileID"]
  readonly scope: Endpoint19_31Request["payload"]["scope"]
  readonly gameID?: Endpoint19_31Request["payload"]["gameID"]
  readonly saveSlotID?: Endpoint19_31Request["payload"]["saveSlotID"]
  readonly characterID?: Endpoint19_31Request["payload"]["characterID"]
  readonly kind: Endpoint19_31Request["payload"]["kind"]
  readonly text: Endpoint19_31Request["payload"]["text"]
  readonly sourceID: Endpoint19_31Request["payload"]["sourceID"]
  readonly confidence: Endpoint19_31Request["payload"]["confidence"]
  readonly importance: Endpoint19_31Request["payload"]["importance"]
  readonly lifecycle: Endpoint19_31Request["payload"]["lifecycle"]
  readonly pinned: Endpoint19_31Request["payload"]["pinned"]
  readonly conflictsWith: Endpoint19_31Request["payload"]["conflictsWith"]
  readonly embedding?: Endpoint19_31Request["payload"]["embedding"]
  readonly embeddingModel?: Endpoint19_31Request["payload"]["embeddingModel"]
  readonly createdAt: Endpoint19_31Request["payload"]["createdAt"]
  readonly updatedAt: Endpoint19_31Request["payload"]["updatedAt"]
  readonly lastUsedAt?: Endpoint19_31Request["payload"]["lastUsedAt"]
}
const Endpoint19_31 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_31Input) =>
  raw["jarvis.remember"]({
    payload: {
      id: input["id"],
      profileID: input["profileID"],
      scope: input["scope"],
      gameID: input["gameID"],
      saveSlotID: input["saveSlotID"],
      characterID: input["characterID"],
      kind: input["kind"],
      text: input["text"],
      sourceID: input["sourceID"],
      confidence: input["confidence"],
      importance: input["importance"],
      lifecycle: input["lifecycle"],
      pinned: input["pinned"],
      conflictsWith: input["conflictsWith"],
      embedding: input["embedding"],
      embeddingModel: input["embeddingModel"],
      createdAt: input["createdAt"],
      updatedAt: input["updatedAt"],
      lastUsedAt: input["lastUsedAt"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_32Request = Parameters<RawClient["server.jarvis"]["jarvis.removeMemory"]>[0]
type Endpoint19_32Input = { readonly memoryID: Endpoint19_32Request["params"]["memoryID"] }
const Endpoint19_32 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_32Input) =>
  raw["jarvis.removeMemory"]({ params: { memoryID: input["memoryID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_33Request = Parameters<RawClient["server.jarvis"]["jarvis.patchMemory"]>[0]
type Endpoint19_33Input = {
  readonly memoryID: Endpoint19_33Request["params"]["memoryID"]
  readonly text?: Endpoint19_33Request["payload"]["text"]
  readonly confidence?: Endpoint19_33Request["payload"]["confidence"]
  readonly importance?: Endpoint19_33Request["payload"]["importance"]
  readonly lifecycle?: Endpoint19_33Request["payload"]["lifecycle"]
  readonly pinned?: Endpoint19_33Request["payload"]["pinned"]
}
const Endpoint19_33 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_33Input) =>
  raw["jarvis.patchMemory"]({
    params: { memoryID: input["memoryID"] },
    payload: {
      text: input["text"],
      confidence: input["confidence"],
      importance: input["importance"],
      lifecycle: input["lifecycle"],
      pinned: input["pinned"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_34Request = Parameters<RawClient["server.jarvis"]["jarvis.resolveMemoryConflict"]>[0]
type Endpoint19_34Input = {
  readonly memoryID: Endpoint19_34Request["params"]["memoryID"]
  readonly action: Endpoint19_34Request["payload"]["action"]
  readonly otherMemoryID: Endpoint19_34Request["payload"]["otherMemoryID"]
}
const Endpoint19_34 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_34Input) =>
  raw["jarvis.resolveMemoryConflict"]({
    params: { memoryID: input["memoryID"] },
    payload: { action: input["action"], otherMemoryID: input["otherMemoryID"] },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint19_35 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.reindexMemory"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint19_36Request = Parameters<RawClient["server.jarvis"]["jarvis.memoryUses"]>[0]
type Endpoint19_36Input = {
  readonly memoryID?: Endpoint19_36Request["query"]["memoryID"]
  readonly turnID?: Endpoint19_36Request["query"]["turnID"]
  readonly limit?: Endpoint19_36Request["query"]["limit"]
}
const Endpoint19_36 = (raw: RawClient["server.jarvis"]) => (input?: Endpoint19_36Input) =>
  raw["jarvis.memoryUses"]({
    query: { memoryID: input?.["memoryID"], turnID: input?.["turnID"], limit: input?.["limit"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_37Request = Parameters<RawClient["server.jarvis"]["jarvis.recordMemoryUse"]>[0]
type Endpoint19_37Input = {
  readonly turnID: Endpoint19_37Request["payload"]["turnID"]
  readonly memoryID: Endpoint19_37Request["payload"]["memoryID"]
  readonly rank: Endpoint19_37Request["payload"]["rank"]
  readonly lexicalScore?: Endpoint19_37Request["payload"]["lexicalScore"]
  readonly semanticScore?: Endpoint19_37Request["payload"]["semanticScore"]
  readonly reason: Endpoint19_37Request["payload"]["reason"]
}
const Endpoint19_37 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_37Input) =>
  raw["jarvis.recordMemoryUse"]({
    payload: {
      turnID: input["turnID"],
      memoryID: input["memoryID"],
      rank: input["rank"],
      lexicalScore: input["lexicalScore"],
      semanticScore: input["semanticScore"],
      reason: input["reason"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_38Request = Parameters<RawClient["server.jarvis"]["jarvis.replays"]>[0]
type Endpoint19_38Input = { readonly limit?: Endpoint19_38Request["query"]["limit"] }
const Endpoint19_38 = (raw: RawClient["server.jarvis"]) => (input?: Endpoint19_38Input) =>
  raw["jarvis.replays"]({ query: { limit: input?.["limit"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_39Request = Parameters<RawClient["server.jarvis"]["jarvis.recordReplay"]>[0]
type Endpoint19_39Input = {
  readonly turnID?: Endpoint19_39Request["payload"]["turnID"]
  readonly sessionID?: Endpoint19_39Request["payload"]["sessionID"]
  readonly surface: Endpoint19_39Request["payload"]["surface"]
  readonly status?: Endpoint19_39Request["payload"]["status"]
  readonly events: Endpoint19_39Request["payload"]["events"]
  readonly metrics?: Endpoint19_39Request["payload"]["metrics"]
  readonly error?: Endpoint19_39Request["payload"]["error"]
}
const Endpoint19_39 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_39Input) =>
  raw["jarvis.recordReplay"]({
    payload: {
      turnID: input["turnID"],
      sessionID: input["sessionID"],
      surface: input["surface"],
      status: input["status"],
      events: input["events"],
      metrics: input["metrics"],
      error: input["error"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_40Request = Parameters<RawClient["server.jarvis"]["jarvis.replay"]>[0]
type Endpoint19_40Input = { readonly replayID: Endpoint19_40Request["params"]["replayID"] }
const Endpoint19_40 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_40Input) =>
  raw["jarvis.replay"]({ params: { replayID: input["replayID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_41Request = Parameters<RawClient["server.jarvis"]["jarvis.removeReplay"]>[0]
type Endpoint19_41Input = { readonly replayID: Endpoint19_41Request["params"]["replayID"] }
const Endpoint19_41 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_41Input) =>
  raw["jarvis.removeReplay"]({ params: { replayID: input["replayID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_42Request = Parameters<RawClient["server.jarvis"]["jarvis.executeReplay"]>[0]
type Endpoint19_42Input = {
  readonly replayID: Endpoint19_42Request["params"]["replayID"]
  readonly fixtureOnly?: Endpoint19_42Request["payload"]["fixtureOnly"]
}
const Endpoint19_42 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_42Input) =>
  raw["jarvis.executeReplay"]({
    params: { replayID: input["replayID"] },
    payload: { fixtureOnly: input["fixtureOnly"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_43Request = Parameters<RawClient["server.jarvis"]["jarvis.replayExecution"]>[0]
type Endpoint19_43Input = { readonly executionID: Endpoint19_43Request["params"]["executionID"] }
const Endpoint19_43 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_43Input) =>
  raw["jarvis.replayExecution"]({ params: { executionID: input["executionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_44Request = Parameters<RawClient["server.jarvis"]["jarvis.compareReplays"]>[0]
type Endpoint19_44Input = {
  readonly baselineExecutionID: Endpoint19_44Request["payload"]["baselineExecutionID"]
  readonly candidateExecutionID: Endpoint19_44Request["payload"]["candidateExecutionID"]
}
const Endpoint19_44 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_44Input) =>
  raw["jarvis.compareReplays"]({
    payload: { baselineExecutionID: input["baselineExecutionID"], candidateExecutionID: input["candidateExecutionID"] },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint19_45 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.inbox"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint19_46Request = Parameters<RawClient["server.jarvis"]["jarvis.wake"]>[0]
type Endpoint19_46Input = {
  readonly sessionID?: Endpoint19_46Request["payload"]["sessionID"]
  readonly kind: Endpoint19_46Request["payload"]["kind"]
  readonly topic: Endpoint19_46Request["payload"]["topic"]
  readonly text: Endpoint19_46Request["payload"]["text"]
  readonly priority: Endpoint19_46Request["payload"]["priority"]
  readonly notBefore?: Endpoint19_46Request["payload"]["notBefore"]
}
const Endpoint19_46 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_46Input) =>
  raw["jarvis.wake"]({
    payload: {
      sessionID: input["sessionID"],
      kind: input["kind"],
      topic: input["topic"],
      text: input["text"],
      priority: input["priority"],
      notBefore: input["notBefore"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_47Request = Parameters<RawClient["server.jarvis"]["jarvis.dismissInbox"]>[0]
type Endpoint19_47Input = { readonly wakeID: Endpoint19_47Request["params"]["wakeID"] }
const Endpoint19_47 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_47Input) =>
  raw["jarvis.dismissInbox"]({ params: { wakeID: input["wakeID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_48Request = Parameters<RawClient["server.jarvis"]["jarvis.retryInbox"]>[0]
type Endpoint19_48Input = { readonly wakeID: Endpoint19_48Request["params"]["wakeID"] }
const Endpoint19_48 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_48Input) =>
  raw["jarvis.retryInbox"]({ params: { wakeID: input["wakeID"] } }).pipe(Effect.mapError(mapClientError))

const Endpoint19_49 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.companionStatus"]({}).pipe(Effect.mapError(mapClientError))

const Endpoint19_50 = (raw: RawClient["server.jarvis"]) => () =>
  raw["jarvis.companionConfig"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint19_51Request = Parameters<RawClient["server.jarvis"]["jarvis.updateCompanionConfig"]>[0]
type Endpoint19_51Input = {
  readonly enabled: Endpoint19_51Request["payload"]["enabled"]
  readonly schedule: Endpoint19_51Request["payload"]["schedule"]
  readonly timezone: Endpoint19_51Request["payload"]["timezone"]
  readonly catchUpUntil: Endpoint19_51Request["payload"]["catchUpUntil"]
  readonly sources: Endpoint19_51Request["payload"]["sources"]
  readonly updatedAt: Endpoint19_51Request["payload"]["updatedAt"]
}
const Endpoint19_51 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_51Input) =>
  raw["jarvis.updateCompanionConfig"]({
    payload: {
      enabled: input["enabled"],
      schedule: input["schedule"],
      timezone: input["timezone"],
      catchUpUntil: input["catchUpUntil"],
      sources: input["sources"],
      updatedAt: input["updatedAt"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_52Request = Parameters<RawClient["server.jarvis"]["jarvis.runDailyBriefing"]>[0]
type Endpoint19_52Input = {
  readonly trigger?: Endpoint19_52Request["payload"]["trigger"]
  readonly force?: Endpoint19_52Request["payload"]["force"]
}
const Endpoint19_52 = (raw: RawClient["server.jarvis"]) => (input?: Endpoint19_52Input) =>
  raw["jarvis.runDailyBriefing"]({ payload: { trigger: input?.["trigger"], force: input?.["force"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint19_53Request = Parameters<RawClient["server.jarvis"]["jarvis.dailyBriefings"]>[0]
type Endpoint19_53Input = { readonly limit?: Endpoint19_53Request["query"]["limit"] }
const Endpoint19_53 = (raw: RawClient["server.jarvis"]) => (input?: Endpoint19_53Input) =>
  raw["jarvis.dailyBriefings"]({ query: { limit: input?.["limit"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_54Request = Parameters<RawClient["server.jarvis"]["jarvis.dailyBriefing"]>[0]
type Endpoint19_54Input = { readonly briefingID: Endpoint19_54Request["params"]["briefingID"] }
const Endpoint19_54 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_54Input) =>
  raw["jarvis.dailyBriefing"]({ params: { briefingID: input["briefingID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_55Request = Parameters<RawClient["server.jarvis"]["jarvis.prepareCompanionAction"]>[0]
type Endpoint19_55Input = {
  readonly briefingID?: Endpoint19_55Request["payload"]["briefingID"]
  readonly kind: Endpoint19_55Request["payload"]["kind"]
  readonly title: Endpoint19_55Request["payload"]["title"]
  readonly preview: Endpoint19_55Request["payload"]["preview"]
  readonly input: Endpoint19_55Request["payload"]["input"]
  readonly requiredScopes?: Endpoint19_55Request["payload"]["requiredScopes"]
  readonly idempotencyKey: Endpoint19_55Request["payload"]["idempotencyKey"]
  readonly externalRevision?: Endpoint19_55Request["payload"]["externalRevision"]
}
const Endpoint19_55 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_55Input) =>
  raw["jarvis.prepareCompanionAction"]({
    payload: {
      briefingID: input["briefingID"],
      kind: input["kind"],
      title: input["title"],
      preview: input["preview"],
      input: input["input"],
      requiredScopes: input["requiredScopes"],
      idempotencyKey: input["idempotencyKey"],
      externalRevision: input["externalRevision"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_56Request = Parameters<RawClient["server.jarvis"]["jarvis.companionActions"]>[0]
type Endpoint19_56Input = { readonly limit?: Endpoint19_56Request["query"]["limit"] }
const Endpoint19_56 = (raw: RawClient["server.jarvis"]) => (input?: Endpoint19_56Input) =>
  raw["jarvis.companionActions"]({ query: { limit: input?.["limit"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_57Request = Parameters<RawClient["server.jarvis"]["jarvis.approveCompanionAction"]>[0]
type Endpoint19_57Input = {
  readonly actionID: Endpoint19_57Request["params"]["actionID"]
  readonly externalRevision?: Endpoint19_57Request["payload"]["externalRevision"]
}
const Endpoint19_57 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_57Input) =>
  raw["jarvis.approveCompanionAction"]({
    params: { actionID: input["actionID"] },
    payload: { externalRevision: input["externalRevision"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_58Request = Parameters<RawClient["server.jarvis"]["jarvis.cancelCompanionAction"]>[0]
type Endpoint19_58Input = { readonly actionID: Endpoint19_58Request["params"]["actionID"] }
const Endpoint19_58 = (raw: RawClient["server.jarvis"]) => (input: Endpoint19_58Input) =>
  raw["jarvis.cancelCompanionAction"]({ params: { actionID: input["actionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_59Request = Parameters<RawClient["server.jarvis"]["jarvis.companionActionAudit"]>[0]
type Endpoint19_59Input = { readonly limit?: Endpoint19_59Request["query"]["limit"] }
const Endpoint19_59 = (raw: RawClient["server.jarvis"]) => (input?: Endpoint19_59Input) =>
  raw["jarvis.companionActionAudit"]({ query: { limit: input?.["limit"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup19 = (raw: RawClient["server.jarvis"]) => ({
  conversation: Endpoint19_0(raw),
  adoptConversation: Endpoint19_1(raw),
  prewarm: Endpoint19_2(raw),
  admitFinal: Endpoint19_3(raw),
  controlStatus: Endpoint19_4(raw),
  updateMediaState: Endpoint19_5(raw),
  runDiagnostics: Endpoint19_6(raw),
  createTurn: Endpoint19_7(raw),
  currentTurn: Endpoint19_8(raw),
  turn: Endpoint19_9(raw),
  updateTurn: Endpoint19_10(raw),
  cancelTurn: Endpoint19_11(raw),
  presence: Endpoint19_12(raw),
  handoffPresence: Endpoint19_13(raw),
  status: Endpoint19_14(raw),
  config: Endpoint19_15(raw),
  updateConfig: Endpoint19_16(raw),
  benchmarkStatus: Endpoint19_17(raw),
  runBenchmark: Endpoint19_18(raw),
  cancelBenchmark: Endpoint19_19(raw),
  profiles: Endpoint19_20(raw),
  syncProfiles: Endpoint19_21(raw),
  goals: Endpoint19_22(raw),
  createGoal: Endpoint19_23(raw),
  resumeGoal: Endpoint19_24(raw),
  replanGoal: Endpoint19_25(raw),
  cancelGoal: Endpoint19_26(raw),
  recordGoalStep: Endpoint19_27(raw),
  outcomes: Endpoint19_28(raw),
  completeGoal: Endpoint19_29(raw),
  searchMemory: Endpoint19_30(raw),
  remember: Endpoint19_31(raw),
  removeMemory: Endpoint19_32(raw),
  patchMemory: Endpoint19_33(raw),
  resolveMemoryConflict: Endpoint19_34(raw),
  reindexMemory: Endpoint19_35(raw),
  memoryUses: Endpoint19_36(raw),
  recordMemoryUse: Endpoint19_37(raw),
  replays: Endpoint19_38(raw),
  recordReplay: Endpoint19_39(raw),
  replay: Endpoint19_40(raw),
  removeReplay: Endpoint19_41(raw),
  executeReplay: Endpoint19_42(raw),
  replayExecution: Endpoint19_43(raw),
  compareReplays: Endpoint19_44(raw),
  inbox: Endpoint19_45(raw),
  wake: Endpoint19_46(raw),
  dismissInbox: Endpoint19_47(raw),
  retryInbox: Endpoint19_48(raw),
  companionStatus: Endpoint19_49(raw),
  companionConfig: Endpoint19_50(raw),
  updateCompanionConfig: Endpoint19_51(raw),
  runDailyBriefing: Endpoint19_52(raw),
  dailyBriefings: Endpoint19_53(raw),
  dailyBriefing: Endpoint19_54(raw),
  prepareCompanionAction: Endpoint19_55(raw),
  companionActions: Endpoint19_56(raw),
  approveCompanionAction: Endpoint19_57(raw),
  cancelCompanionAction: Endpoint19_58(raw),
  companionActionAudit: Endpoint19_59(raw),
})

const adaptClient = (raw: RawClient) => ({
  health: adaptGroup0(raw["server.health"]),
  location: adaptGroup1(raw["server.location"]),
  agents: adaptGroup2(raw["server.agent"]),
  sessions: adaptGroup3(raw["server.session"]),
  messages: adaptGroup4(raw["server.message"]),
  models: adaptGroup5(raw["server.model"]),
  providers: adaptGroup6(raw["server.provider"]),
  integrations: adaptGroup7(raw["server.integration"]),
  credentials: adaptGroup8(raw["server.credential"]),
  permissions: adaptGroup9(raw["server.permission"]),
  files: adaptGroup10(raw["server.fs"]),
  commands: adaptGroup11(raw["server.command"]),
  skills: adaptGroup12(raw["server.skill"]),
  events: adaptGroup13(raw["server.event"]),
  ptys: adaptGroup14(raw["server.pty"]),
  questions: adaptGroup15(raw["server.question"]),
  references: adaptGroup16(raw["server.reference"]),
  projectCopies: adaptGroup17(raw["server.projectCopy"]),
  repositoryMap: adaptGroup18(raw["server.repositoryMap"]),
  "server.jarvis": adaptGroup19(raw["server.jarvis"]),
})

export const make = (options?: { readonly baseUrl?: URL | string }) =>
  HttpApiClient.make(ClientApi, options).pipe(Effect.map(adaptClient))
